import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font"

[window]
decorations = "Buttonless"
option_as_alt = "Both"
dynamic_padding = true
padding = { x = 5, y = 5 }
